const isProduction = process.env.NODE_ENV === 'production';

module.exports = {
  plugins: [
    require('postcss-import'),
    require('tailwindcss/nesting'),
    require('tailwindcss'),
    require('autoprefixer'),
    // Only enable CSS minification in production
    isProduction && require('cssnano')({
      preset: ['default', {
        discardComments: {
          removeAll: true,
        },
      }],
    }),
    // Only enable PurgeCSS in production
    isProduction && require('@fullhuman/postcss-purgecss')({
      content: [
        './src/**/*.{js,jsx,ts,tsx}',
        './public/index.html'
      ],
      defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || [],
      safelist: [
        /data-theme$/,
        /^theme-/,
        /^dark/,
        /^light/,
        /^bg-/,
        /^text-/,
        /^border-/,
        /^hover:bg-/, 
        /^hover:text-/, 
        /^focus:ring-/, 
        /^focus:border-/, 
        /^focus:outline-/, 
        /^active:bg-/, 
        /^transition-/, 
        /^duration-/, 
        /^ease-/, 
        /^delay-/, 
        /^animate-/, 
        /^opacity-/, 
        /^scale-/, 
        /^rotate-/, 
        /^translate-/, 
        /^transform/, 
        /^group-hover:/, 
        /^group-focus:/, 
        /^focus-visible:/, 
        /^motion-safe:/, 
        /^motion-reduce:/, 
        /^print:/, 
        /^dark:/, 
        /^sm:/, 
        /^md:/, 
        /^lg:/, 
        /^xl:/, 
        /^2xl:/, 
        /^first:/, 
        /^last:/, 
        /^odd:/, 
        /^even:/, 
        /^visited:/, 
        /^checked:/, 
        /^focus-within:/, 
        /^hover:scale-/, 
        /^hover:rotate-/, 
        /^hover:translate-/, 
        /^hover:opacity-/, 
        /^focus:ring-/, 
        /^focus:border-/, 
        /^focus:outline-/, 
        /^focus:shadow-/, 
        /^active:scale-/, 
        /^active:opacity-/, 
        /^disabled:opacity-/, 
        /^disabled:cursor-/, 
        /^aria-/, 
        /^data-/, 
        /^\[\w+-?\w*:?\]/, 
        /^\[\w+=\w+\]/, 
        /^\[\w+~?=\w+\]/, 
        /^\[\w+\|=\w+\]/, 
        /^\[\w+\^=\w+\]/, 
        /^\[\w+\$=\w+\]/, 
        /^\[\w+\*=\w+\]/, 
      ],
    }),
  ].filter(Boolean),
};